service: s3-file-uploader

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

custom:
  fileUploadBucketName: s3-api-testbucket-1213131

resources:
 Resources:
  FileBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: s3-api-testbucket-1213131
      AccessControl: PublicRead
